<?php

/**
 * @file
 * Install, update and uninstall functions for the farmOS installation profile.
 */

declare(strict_types=1);

/**
 * Implements hook_install_tasks().
 */
function farm_install_tasks(&$install_state) {

  // Add tasks for configuring farmOS and installing base modules.
  $tasks = [
    'farm_install_config' => [
      'type' => 'normal',
    ],
    'farm_install_base_modules' => [
      'type' => 'normal',
    ],
  ];
  return $tasks;
}

/**
 * Implements hook_install_tasks_alter().
 */
function farm_install_tasks_alter(&$tasks, $install_state) {

  // Override install task display names to replace "site" with the
  // distribution name.
  $alter_display_names = [
    'install_profile_modules' => t('Install ChengetAi Farm Manager'),
    'install_configure_form' => t('Configure ChengetAi Farm Manager'),
  ];
  foreach ($alter_display_names as $task => $display_name) {
    if (!empty($tasks[$task]['display_name'])) {
      $tasks[$task]['display_name'] = $display_name;
    }
  }
}

/**
 * Install default farmOS configuration.
 */
function farm_install_config() {

  // Use private file system by default.
  \Drupal::configFactory()->getEditable('system.file')->set('default_scheme', 'private')->save();

  // Only allow admins to register new users.
  \Drupal::configFactory()->getEditable('user.settings')->set('register', 'admin_only')->save();
}

/**
 * Installs farmOS base modules.
 *
 * @param array $install_state
 *   An array of information about the current installation state.
 */
function farm_install_base_modules(array $install_state): void {

  // If the --existing-config flag is set, do not install base modules.
  // We assume that a site that is using configuration management has made its
  // own decisions about which modules should be installed. By installing any
  // additional modules here we could end up with overridden configuration. For
  // example, it is possible that some of the optional base modules have been
  // uninstalled in these instances, and we should not reinstall them.
  if (!empty($install_state['parameters']['existing_config']) && $install_state['parameters']['existing_config'] === TRUE) {
    return;
  }

  // Skip base module installation if this is running in the context of a
  // functional test.
  // @see Drupal\Tests\farm_test\Functional\FarmBrowserTestBase::setUp()
  if (!empty($GLOBALS['farm_test'])) {
    return;
  }

  // Install base modules.
  $modules = [
    'farm_login',
    'farm_setup',
    'farm_ui',
    'farm_update',
  ];
  \Drupal::service('module_installer')->install($modules, TRUE);

  // Initialize the setup wizard state so that the welcome form is displayed on
  // the dashboard.
  \Drupal::service('farm_setup.wizard')->setBlockPluginId('welcome');
}
