<?php

/**
 * @file
 * Install, update and uninstall functions for the farm_ui_theme module.
 */

declare(strict_types=1);

use Drupal\block\Entity\Block;

/**
 * Implements hook_install().
 */
function farm_ui_theme_install() {

  // Install the Gin theme and make it the default.
  \Drupal::service('theme_installer')->install(['gin']);
  \Drupal::configFactory()->getEditable('system.theme')->set('default', 'gin')->save();

  // Load Gin settings.
  $gin_settings = \Drupal::configFactory()->getEditable('gin.settings');

  // Use vertical toolbar.
  $gin_settings->set('classic_toolbar', 'vertical');

  // Use green/orange color palette.
  $gin_settings->set('preset_accent_color', 'green');
  $gin_settings->set('preset_focus_color', 'orange');

  // Use ChengetAi Farm Manager logo and favicon.
  $path = \Drupal::service('extension.list.module')->getPath('farm_ui_theme');
  $gin_settings->set('logo.use_default', FALSE);
  $gin_settings->set('logo.path', $path . '/logo.png');
  $gin_settings->set('favicon.use_default', FALSE);
  $gin_settings->set('favicon.path', $path . '/favicon.ico');

  // Users can override Gin settings.
  $gin_settings->set('show_user_theme_settings', TRUE);

  // Save Gin settings.
  $gin_settings->save();

  // Create the "Powered by ChengetAi Farm Manager" block.
  // This must be done in hook_install() instead of config/install because Gin
  // needs to be installed first.
  $values = [
    'id' => 'farm_powered',
    'plugin' => 'farm_powered_by_block',
    'theme' => 'gin',
    'region' => 'content',
    'weight' => 1000,
    'settings' => [
      'id' => 'farm_powered_by_block',
      'label' => t('Powered by ChengetAi Farm Manager'),
      'provider' => 'farm_ui_theme',
      'label_display' => '0',
    ],
    'visibility' => [],
    'dependencies' => [
      'enforced' => [
        'module' => [
          'farm_ui_theme',
        ],
      ],
    ],
  ];
  Block::create($values)->save();
}

/**
 * Implements hook_update_dependencies().
 */
function farm_ui_theme_update_dependencies() {

  // Ensure that this module's farm_ui_theme_update_11400 update (which installs
  // farm_form) runs before farm_entity module's farm_entity_update_11400 update
  // (which installs farm_entity_access). The farm_form module provides a trait
  // used by farm_ui_theme, and if another module is installed before farm_form
  // then a fatal error is thrown if anything loads a class that depends on the
  // trait.
  // @see https://github.com/farmOS/farmOS/issues/1062
  $dependencies['farm_entity'][11400] = [
    'farm_ui_theme' => 11400,
  ];
  return $dependencies;
}

/**
 * Install the farm_form module.
 */
function farm_ui_theme_update_11400() {
  if (!\Drupal::service('module_handler')->moduleExists('farm_form')) {
    \Drupal::service('module_installer')->install(['farm_form']);
  }
}

/**
 * Implements hook_update_last_removed().
 */
function farm_ui_theme_update_last_removed() {
  return 9001;
}
